remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Jared Holgate's Blog
description: |
  Jared Holgates's Blog Site
show_downloads: true
url: https://jaredholgate.co.uk
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
